//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GistBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GistBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded Gist {0}..
        /// </summary>
        internal static string Info_Get {
            get {
                return ResourceManager.GetString("Info_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully posted Gist!.
        /// </summary>
        internal static string Info_Post {
            get {
                return ResourceManager.GetString("Info_Post", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tray_Context_Config_Icon {
            get {
                object obj = ResourceManager.GetObject("Tray_Context_Config_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Configuration....
        /// </summary>
        internal static string Tray_Context_Config_Text {
            get {
                return ResourceManager.GetString("Tray_Context_Config_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tray_Context_Download_Icon {
            get {
                object obj = ResourceManager.GetObject("Tray_Context_Download_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Download....
        /// </summary>
        internal static string Tray_Context_Download_Text {
            get {
                return ResourceManager.GetString("Tray_Context_Download_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tray_Context_Post_Icon {
            get {
                object obj = ResourceManager.GetObject("Tray_Context_Post_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Post clipboard....
        /// </summary>
        internal static string Tray_Context_Post_Text {
            get {
                return ResourceManager.GetString("Tray_Context_Post_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string Tray_Context_Quit_Text {
            get {
                return ResourceManager.GetString("Tray_Context_Quit_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Tray_Icon {
            get {
                object obj = ResourceManager.GetObject("Tray_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistBoard.
        /// </summary>
        internal static string Tray_Text {
            get {
                return ResourceManager.GetString("Tray_Text", resourceCulture);
            }
        }
    }
}
